language: node_js
node_js:
  - "node"
before_install:
  - npm install -g npm@latest
  - npm --version
  - npm install -g grunt-cli grunt-jest jest-cli node-sass
install:
  - npm install
script:
  - npm start
  - npm test
  - npm run report-coverage